services:
  falcon-init:
    container_name: "falcon-init"
    image: "us-central1-docker.pkg.dev/wb-beamish-lettuce-5001/shared-repo/navid-falcon-node-sensor:latest"
    privileged: true
    pid: host
    network_mode: host
    ipc: host
    entrypoint: /opt/CrowdStrike/falcon-daemonset-init
    command: ["-i"]
    volumes:
      - /opt/CrowdStrike/falconstore:/opt/CrowdStrike/falconstore

  falcon-sensor:
    container_name: "falcon-sensor"
    image: "us-central1-docker.pkg.dev/wb-beamish-lettuce-5001/shared-repo/navid-falcon-node-sensor:latest"
    privileged: true
    pid: host
    network_mode: host
    ipc: host
    userns_mode: host
    restart: always
    volumes:
      - /opt/CrowdStrike/falconstore:/opt/CrowdStrike/falconstore
    depends_on:
      falcon-init:
        condition: service_completed_successfully

  app:
    container_name: "application-server"
    image: "us-central1-docker.pkg.dev/wb-beamish-lettuce-5001/shared-repo/base-image:2.6.0"
    restart: always
    entrypoint: /bin/bash
    command: >
      -c "/usr/bin/workstation-startup || true; runuser user -c 'sleep infinity'"
    volumes:
      - .:/workspace:cached
      - work:/home/user:cached
    ports:
      - "8080:80"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor=unconfined
    depends_on:
      - falcon-sensor

networks:
  app-network:
    external: true

volumes:
  work:
