services:
  app:
    container_name: "application-server"
    image: "us-central1-docker.pkg.dev/wb-beamish-lettuce-5001/shared-repo/base-image-protected:2.6.0"
    restart: always
    entrypoint: /opt/CrowdStrike/rootfs/bin/falcon-entrypoint
    command: >
      /bin/bash -c "/usr/bin/workstation-startup || true; runuser user -c 'sleep infinity'"
    environment:
      - CONTAINER_APP_NAME=super-vscode-app
    volumes:
      - .:/workspace:cached
      - work:/home/user:cached
    ports:
      - "8080:80"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor=unconfined

networks:
  app-network:
    external: true

volumes:
  work:
